# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineral',
            name='created_at',
        ),
    ]
